dataimport/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'dataimport'
urlpatterns = [
    path('', views.index, name='index'),

    # ex: /polls/5/
    path('<int:filename_id>/', views.detail, name='detail'),
    path('upload/', views.model_form_upload, name='model_form_upload'),
    path('<int:pk>/run_processing/', views.run_processing, name='run_processing'),
]

microimprocessing/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'microimprocessing'
urlpatterns = [
    path('', views.index, name='index'),

    # ex: /polls/5/
    path('<int:filename_id>/', views.set_lobules_seeds, name='set_lobules_seeds'),
    path('<int:filename_id>/detail', views.detail, name='detail'),
    path('<int:filename_id>/file_log', views.file_log, name='file_log'),
    path('<int:filename_id>/create_and_download_zip', views.create_and_download_zip, name='create_and_download_zip'),
    path('common_spreadsheet', views.common_spreadsheet, name='common_spreadsheet'),
    path('upload/', views.model_form_upload, name='model_form_upload'),
    path('show_tag/<int:tag_id>', views.show_tag, name='show_tag'),
    path('hide_tag/<int:tag_id>', views.hide_tag, name='hide_tag'),
    path('ignore_tag/<int:tag_id>', views.ignore_tag, name='ignore_tag'),
    path('remove_tag_from_user/<int:tag_id>', views.remove_tag_from_user, name='remove_tag_from_user'),
    path('create_tag/', views.create_tag, name='create_tag'),
    path('create_tag/<int:filename_id>', views.create_tag, name='create_and_add_tag'),
    path('<int:filename_id>/add_tag/<int:tag_id>', views.add_tag, name='add_tag'),
    path('<int:filename_id>/remove_tag/<int:tag_id>', views.remove_tag, name='remove_tag'),
    path('create_report/', views.create_report, name='create_report'),
    path('gdrive_import/', views.gdrive_import, name='gdrive_import'),
    path('<int:pk>/run_processing/', views.run_processing, name='run_processing'),
    path('logout/', views.logout_view, name='logout_view'),
    path('add_example_data/', views.add_example_data, name='add_example_data'),
    path('<int:filename_id>/delete_file/', views.delete_file, name='delete_file'),
    path('force_update/', views.force_update, name='force_update'),
    # path('generic_files/', views.GenericFileListView.as_view()),
    path('set_order_by/<str:order_by>', views.set_order_by, name='set_order_by'),
    path('<int:filename_id>/pre_run/', views.pre_run, name='pre_run'),
]

scaffanweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView # <--
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from loguru import logger

urlpatterns = [
    path('wellcome/', TemplateView.as_view(template_name='microimprocessing/wellcome.html')), # <--I
    # path('', TemplateView.as_view(template_name='microimprocessing/login.html')), # <--I
    path('', TemplateView.as_view(template_name='microimprocessing/login.html'), name="login"), # <--I
    path('microimprocessing/', include('microimprocessing.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # <--
]
# urlpatterns += staticfiles_urlpatterns() # this is almost equal with fallowing line but this should be used for development only
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# print (static(settings.MEDIA_URL))
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microimprocessing/forms.py
from django import forms
from .models import ServerDataFileName, Tag
from loguru import logger


class ImageQuatroForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     self.owner_user = kwargs.pop('owner', None)
    #     super(ImageQuatroForm, self).__init__(*args, **kwargs)
    class Meta:
        model = ServerDataFileName
        fields = ('description', 'imagefile', "annotationfile")

class TagForm(forms.ModelForm):
    # def __init__(self, *args, **kwargs):
    #     self.owner_user = kwargs.pop('owner', None)
    #     super(ImageQuatroForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Tag
        fields = ('name', )

class QueryForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)


class ScaffanParameters(forms.Form):
    # renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    # name = forms.CharField(disabled=True)
    # value = forms.CharField(help_text="Parameters to update")

    def __init__(self, *args, **kwargs):
         super(ScaffanParameters, self).__init__(*args, **kwargs)
         import scaffan.algorithm
         mainapp = scaffan.algorithm.Scaffan()
         # parameters_as_cfg_string = mainapp.get_parameters_as_cfg_string()
         dct = mainapp.parameters_to_dict()
         # Remove parameters from Input and Output
         dct = {key: val for key, val in dct.items() if not key.startswith("Input;") and not key.startswith("Output;")}
         dct.pop("Processing;Show")
         dct.pop("Processing;Open output dir")

         # dynamic fields here ...
         # self.fields['plan_id'] = forms.CharField()
         for element in dct:
             p = mainapp.parameters.param(*element.split(";"))
             help_text = p.opts["tip"] if "tip" in p.opts else ""
             tp = p.opts['type']
             logger.debug(f"element {element} {type(dct[element])} {tp}")
             # if type(dct[element]) == bool:
             if tp == 'bool':
                 self.fields[element] = forms.BooleanField(initial=dct[element], required=False, help_text=help_text)
             elif tp == 'float':
                 self.fields[element] = forms.FloatField(initial=dct[element], required=False, help_text=help_text)
             elif tp == 'int':
                 self.fields[element] = forms.IntegerField(initial=dct[element], required=False, help_text=help_text)
             else:
                 self.fields[element] = forms.CharField(initial=dct[element], required=False, help_text=help_text)

microimprocessing/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import logout
from django.core.files.base import ContentFile
from .models import get_output_dir, Tag
from .forms import ImageQuatroForm, TagForm, ScaffanParameters
from .tasks import make_thumbnail, get_zip_fn, make_zip
from pathlib import Path
from django.conf import settings
from django.views.generic import ListView
from django.http import HttpResponse
from datetime import datetime
from microimprocessing import models, tasks
import sys
# pth = str(Path(__file__).parent.parent.parent / "scaffan")
# print(f"local scaffan path={pth}")
# sys.path.insert(0, pth)
# print(f"PATH={sys.path}")
import os.path as op
from loguru import logger
import numpy as np
import django_q
import glob
import os.path
import pprint

from .models import ServerDataFileName, LobuleCoordinates, ExampleData, User, GDriveImport


def index(request):
    # latest_question_list = ServerDataFileName.objects.order_by('-pub_date')[:5]
    # latest_filenames = ServerDataFileName.objects.all()
    hide_tags = request.session.get("hide_tags", [])
    show_tags = request.session.get("show_tags", [])
    logger.trace(f"hide_tags={hide_tags}")
    logger.trace(f"show_tags={show_tags}")
    logger.debug(f"Preparing index view for {request.user}")
    order_by = request.session.get("order_by", '-uploaded_at')
    order_by_items_input = [
        "uploaded_at",
        "started_at",
        "filename"
    ]

    order_by_items = []
    for field in order_by_items_input:
        if field == 'filename':
            title = "Filename"
        else:
            title = models.ServerDataFileName._meta.get_field(field).verbose_name.title()
        order_by_items.append([
            field,
            "▲ " + title,
            # "&#9650; " + title,
            field == order_by
        ])
        order_by_items.append([
            "-" + field,
            "▼ " + title,
            # "&#9660; " + title,
            ("-" + field) == order_by
        ])

    # logger.warning(order_by_items)
    logger.trace("getting filenames")
    qs_latest_filenames = ServerDataFileName.objects.filter(
        owner=request.user,
        ).exclude(
        tag__in=hide_tags
    )
    logger.trace("preparing tags")
    if len(show_tags) > 0:
        qs_latest_filenames = qs_latest_filenames.filter(tag__in=request.session.get("show_tags", []))

    if order_by == "filename":
        latest_filenames = sorted(qs_latest_filenames, key=lambda i: i.filename, reverse=False)
    elif order_by  == "-filename":
        latest_filenames = sorted(qs_latest_filenames, key=lambda i: i.filename, reverse=True)
    else:
        latest_filenames = qs_latest_filenames.order_by(order_by)

    logger.trace("getting number of points ...")
    number_of_points = [
        len(LobuleCoordinates.objects.filter(server_datafile=serverfile))
        for serverfile in latest_filenames
    ]
    output_exists = [
        (Path(serverfile.outputdir) / "data.xlsx").exists()
        for serverfile in latest_filenames
    ]

    # for serverfile in latest_filenames:
    #     if (Path(serverfile.outputdir) / "data.xlsx").exists():
    #         logger.debug(f"output exists: {serverfile.outputdir}")
    #         zip_fn = get_zip_fn(serverfile)
    #         if zip_fn:
    #             if not Path(zip_fn).exists():
    #                 make_zip(serverfile)
    #                 serverfile.process_started = False
    #                 serverfile.save()
    logger.trace("check zip exists")
    zip_exists = [
        Path(get_zip_fn(serverfile)).exists() if get_zip_fn(serverfile) else False
        for serverfile in latest_filenames
    ]
    logger.trace("collecting possible errors")
    file_error = [
        _find_error(serverfile)[0]
        # None if Path(serverfile.imagefile.path).exists() else "File not found on the server" if get_zip_fn(serverfile) else False
        for serverfile in latest_filenames
    ]
    logger.trace("setting tags...")
    files_tags = [serverfile.tag_set.all()
        for serverfile in latest_filenames
    ]

    logger.trace("getting common spreadsheet file")
    fn, spreadsheet_url, name = models.get_common_spreadsheet_file(request.user)
    spreadsheet_exists = fn.exists()

    # latest_filenames_short = [
    #     Path(fn.imagefile.path).name for fn in latest_filenames
    #     ]
    # template = loader.get_template('microimprocessing/index.html')
    # if request.user in gdriveimport.user.all():

    logger.trace("preparing gdrive import")
    user_has_gdrive_import = (len(models.GDriveImport.objects.filter(user=request.user)) > 0)

    user_tags = [
        (
            tag,
            "show" if tag.id in request.session.get("show_tags", []) else
            "hide" if tag.id in request.session.get("hide_tags", []) else
            "ignore"
        ) for tag in  request.user.tag_set.all()]
    context = {
        'latest_filenames': zip(
            latest_filenames,
            number_of_points,
            output_exists,
            zip_exists,
            files_tags,
            file_error
        ),
        "spreadsheet_exists": spreadsheet_exists,
        "spreadsheet_url": spreadsheet_url,
        "user_tags": user_tags,
        "user_has_gdrive_import": user_has_gdrive_import,
        "order_by": order_by,
        "order_by_items": order_by_items,
        # "n_points": number_of_points,
    }
    # return HttpResponse(template.render(context, request))
    logger.debug("Index view almost finished. Rendering...")
    return render(request, 'microimprocessing/index.html', context)
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


def create_and_download_zip(request, filename_id):
    serverfile = get_object_or_404(ServerDataFileName, pk=filename_id)
    zip_fn = get_zip_fn(serverfile)
    if zip_fn:
        make_zip(serverfile)
        serverfile.process_started = False
        serverfile.save()
    return redirect(serverfile.zip_file.url)


def _find_error(serverfile:ServerDataFileName):

    msg = ''
    if (not Path(serverfile.imagefile.path).exists()) and get_zip_fn( serverfile):
        msg += "File not found on the server. "
        # is_failed = [fn in first_arg_of_failed_tasks for fn in latest_filenames]
    # tasks_of_file = [tsk for tsk in django_q.models.Task.objects.all().order_by('-started') if
    #                      ((len(tsk.args) > 0) and (tsk.args[0] == serverfile))]

    # if len(tasks_of_file) > 0:
    #     last_task = tasks_of_file[0]
    if serverfile.last_task_uuid:
        last_task = django_q.models.Task.get_task(serverfile.last_task_uuid)
        if last_task is None:
            msg += f"Task {serverfile.last_task_uuid} not found. "
        elif last_task.success:
            pass
        else:
            msg += f"Failed task. Func: {last_task.func}, Short result: {last_task.short_result}"
    else:
        last_task = None



    return msg, last_task


def delete_file(request, filename_id):
    serverfile = get_object_or_404(ServerDataFileName, pk=filename_id)
    serverfile.delete()
    return redirect('/microimprocessing/')


# class GenericFileListView(ListView):
#     # not used
#     model = ServerDataFileName
#
#     def head(self, *args, **kwargs):
#         last_book = self.get_queryset().latest('upladed_at')
#         response = HttpResponse()
#         # RFC 1123 date format
#         response['Last-Modified'] = last_book.publication_date.strftime('%a, %d %b %Y %H:%M:%S GMT')
#         return response
#

def force_update(request):
    """
    Used to generate few things automatically. Usually used for debug.
    :param request:
    :return:
    """
    from django_q.tasks import async_task
    # logger.debug(f"parameters={parameters}")
    tid = async_task(
        'microimprocessing.tasks.force_update_task',
        # hook="microimprocessing.views.make_thumbnail"
        # hook='microimprocessing.tasks.finish_processing',
    )

    return redirect('/microimprocessing/')


def file_log(request, filename_id):
    serverfile = get_object_or_404(ServerDataFileName, pk=filename_id)
    msg, task = _find_error(serverfile)
    logger.debug(f"task={task}")
    logger.debug(f"serverfile.last_task_uuid={serverfile.last_task_uuid}")
    key_value = {}
    if task:
        key_value = {
            'Id': task.id,
            'Name': task.name,
            'Func': task.func,
            'Hook': task.hook,
            'Args': ", ".join(map(str, task.args)),
            'Kwargs': ", ".join(map(str, task.kwargs)),
            'Result': "None" if task.result is None else task.result.replace('\n', '<br>'),
            'Group': task.group,
            # "Started by user": serverfile.started_at,
            "Added to queue": serverfile.started_at,
            'Started': task.started,
            'Stopped': task.stopped,
            "Success": task.success,
            "Queue size": django_q.tasks.queue_size(),
            "Queue length": len(django_q.models.Task.objects.all()),
            "Queue tasks": pprint.pformat(django_q.models.Task.objects.all().order_by('-started')[:10]),
        }

        # if not task.success:
        #     key_value = {
        #         'Id': task.id,
        #         'Name': task.name,
        #         'Func': task.func,
        #         'Hook': task.hook,
        #         'Args': ", ".join(map(str, task.args)),
        #         'Kwargs': ", ".join(map(str, task.kwargs)),
        #         'Result': task.result.replace('\n', '<br>'),
        #         'Group': task.group,
        #         'Started': task.started,
        #         'Stopped': task.stopped,
        #         "Success": task.success,
        #     }

    if (len(msg) > 0) and ((task is None) or task.success):
        key_value = {"Error": msg}

    opath = Path(serverfile.outputdir)
    # outputdir_url = opath.exists()

microimprocessing/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <!-- ajax-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!--    icons-->
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- <script src='https://kit.fontawesome.com/a076d05399.js'></script> -->
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://use.fontawesome.com/releases/v5.1.0/css/all.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>



    <link rel="stylesheet" href="{% static 'microimprocessing/main.css' %}" type="text/css" />
    <script src="{% static 'microimprocessing/main.js' %}"></script> <!-- This is how to include a static file -->
    <title>ScaffAn</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'microimprocessing/favicon.ico' %}"/>
    <!-- link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <!-- Latest compiled and minified JavaScript -->
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->

    {% block head %}
    {% endblock %}
    <script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>
</head>

<body>
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<!--    <div class="jumbotron p-1">-->
<nav class="navbar navbar-expand-sm bg-light">
<!--<nav class="navbar navbar-default ">-->
<!--    <div class="container-fluid">-->

<!--        <div class="float-left">-->
<!--    <a href="{% url 'microimprocessing:index' %}" >-->
<!--        <div class="navbar-header">-->

            <a class="navbar-brand" href="{% url 'login' %}" >
                <img id="scaffanlogo" class="m-0" src="{% static 'microimprocessing/scaffan_icon512.png' %}" alt="ScaffAn">
            </a>
<!--        </div>-->
<!--    <ul class="nav navbar-nav">-->
    <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated %}
        <li class="nav-item">
            <div class="btn">
                {{ user.username }}
            </div>
        </li>
        <li class="nav-item">
            <a class="btn btn-light" href="{% url 'microimprocessing:logout_view' %}">Logout
<!--                <i class="fas fa-sign-out-alt" aria-hidden="true"></i>-->
            </a>
        </li>
        {% endif %}
    </ul>
<!--    </div>-->

</nav>
<!--    </div>-->

<!--<nav class="navbar navbar-default">-->
<!--  <div class="container-fluid">-->
<!--    <div class="navbar-header">-->
<!--      <a class="navbar-brand" href="#">WebSiteName</a>-->
<!--    </div>-->
<!--    <ul class="nav navbar-nav">-->
<!--      <li class="active"><a href="#">Home</a></li>-->
<!--      <li><a href="#">Page 1</a></li>-->
<!--      <li><a href="#">Page 2</a></li>-->
<!--      <li><a href="#">Page 3</a></li>-->
<!--    </ul>-->
<!--  </div>-->
<!--</nav>-->
<!--    <div class="jumbotron p-0">-->
<!--        <img id="scaffanlogo" class="m-0" src="{% static 'microimprocessing/scaffan_icon512.png' %}" alt="ScaffAn">-->
<!--        <h1>ScaffAn</h1>-->
<!--        <a class="btn btn-secondary ml-auto" href="{% url 'microimprocessing:logout_view' %}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i></a>-->
<!--    </div>-->

<!--    <div id="myDiv" class="container-fluid-xl" >-->
    <div id="myDiv">
<!--    <div class="container-fluid" >-->
<!--        <div class="row content">-->
<!--            <div class="col-md-1 sidenav bg-light">-->
<!--                <a href="{% url 'microimprocessing:index' %}" >-->
<!--                    <img id="scaffanlogo" class="m-0" src="{% static 'microimprocessing/scaffan_icon512.png' %}" alt="ScaffAn">-->
<!--                </a>-->
<!--                <p>-->
<!--                    ahoj-->
<!--                </p>-->
<!--            </div>-->
<!--            <div class="col-md-9">-->
<!--                <div id="myDiv" class="container-fluid">-->
<!--                <div id="myDiv" class="container">-->

<!--                    <div id="appbody" class="container">-->
                    <div id="appbody">
<!--                        <div class="container">-->
                            {% block body %}
                            {% endblock %}
                            {% block content %}
                            {% endblock %}
<!--                        </div>-->
                    </div>
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>